### ISSUE TITLE
Unclear instructions how to enable  

### ISSUE THREAD

**Issue by olexiyb** [jenkinsci/jetbrains-space-plugin#22]
### Describe your use-case which is not covered by existing documentation.

I do not see the "Featured Integrations page" in "Administration"

![image](https://github.com/jenkinsci/jetbrains-space-plugin/assets/352780/bdce6fb6-23a5-4e94-92a3-e951b1153027)

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

Jenkins integration can be enabled on the Featured Integrations page of the Administration section in JetBrains Space. Navigate to this page and click the Enable button for Jenkins integration.

**Comment by olexiyb** [comment]
Another issue in next
```
Configure Space integration in Jenkins
Install this plugin to your Jenkins instance. This is done via the Jenkins > Manage Jenkins > Manage Plugins menu in Jenkins.
```
There is no "Manage Plugins"
![image](https://github.com/jenkinsci/jetbrains-space-plugin/assets/352780/39eb78e0-970a-4337-90e7-6e9c67f949cd)

**Comment by Kiryushin-Andrey** [comment]
Thank you for reporting and sorry for the late response! The mentioned "Featured Integrations" page is indeed an unintended sneak peak into the future, it is currently under development and not yet released. Currently there is no workaround to set up the integration with the current version of JetBrains Space, so need to wait for the updates of both Space and this plugin to be released. I'll keep this issue opened and will post you additionally here when the Jenkins plugin will be updated and ready to use with the cloud JetBrains Space version.

**Comment by Kiryushin-Andrey** [comment]
@olexiyb Jenkins integration has finally been released and is now available for all cloud JetBrains Space organizations. The documentation has been updated as well. I'm closing the ticket, but if you notice any further inconsistencies, please do not hesitate to report them.
